name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - wrestle-circle-ci
  workflow_dispatch:

permissions:
  contents: read

jobs:
  systemtest:
    runs-on: ubuntu-22.04
    env:
      python-version: 3.9
    steps:
      - name: Test image
        run: |
          echo "debian:11-${{ env.python-version }}"
