name: CI

on:
  push:
    branches:
      - "master"
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  systemtest:
    runs-on: ubuntu-22.04
    container:
      image: debian:11
      env:
        python-version: 3.9
      options: --cpus 1
    steps:
      - name: Test image
        run: |
          echo "debian:11-${{ env.python-version }}"
